#!/bin/env bash


function show_logs() {
    tail -n 300 -f $1
}

if [ "$1" = "master" ]; then
    show_logs nohup.out

elif [ "$1" = "pool" ]; then
    uid=`id -u`
    show_logs /tmp/wq-pool-$uid/condor.logfile

elif [ "$1" = "workers" ]; then
    show_logs /tmp/$USER-workers/workers.log

elif [ "$1" = "factory" ]; then
    show_logs "largepyr_2.1_00000000000000000000_nu_bomarchman.factory.out"

else 
    echo "Bad option"
fi